### ISSUE TITLE
V3 of the spacexdata api depreciated 

### ISSUE THREAD

**Issue by mwkrieger** [koxm/MMM-SpaceX#3]
Hi, 

I noticed that my MM wasn't pulling in SpaceX launches anymore. It seems that the root cause is that the spacexdata api has depreciated the V3 version. Now they are on V4. Here's the issue on github: https://github.com/r-spacex/SpaceX-API/issues/564

I changed the V3 to V4 in the settings, but it does not work, so I expect the underlying data structure is different. 

What would be the best way to get the MMM-SpaceX updated to handle the changes?

**Comment by koxm** [comment]
Hi mwkrieger,

I also noticed that the v3 version was no longer supported. Shortly after the release of the SpaceX module I also released a module based on the SpaceLaunchNow api. And personally I like it much better because it also shows other agencys. 

Is that also an option for you?

Regards. 

PS: It's over here: https://github.com/koxm/MMM-SpaceLaunchNow

**Comment by mwkrieger** [comment]
Thanks - yes, I switched over to SpaceLaunchNow and it works fine.
